sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t fdubuisson/influxdb-rpi .
# test image
- docker run fdubuisson/influxdb-rpi influxd --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(docker run fdubuisson/influxdb-rpi influxd version | cut -d ' ' -f 2)
    docker tag fdubuisson/influxdb-rpi fdubuisson/influxdb-rpi:$TAG
    docker push fdubuisson/influxdb-rpi:$TAG
    docker push fdubuisson/influxdb-rpi
  fi
